import { createBrowserRouter, Navigate } from 'react-router-dom'
import { RequireAuth } from '../auth/RequireAuth'
import { RequirePermission } from '../auth/RequirePermission'
import { appRoutes } from './routes'
import { AppShell, ContentPage, CreateProgramPage, CreateResourcePage, DashboardPage, LoginPage, MediaLibraryPage, ProductDetailPage, ProductsPage, ProgramEditorPage, ReleaseComposerPage, ReleasesPage, ResourceDetailPage, RouteBoundary, UserDetailPage, UsersPage } from './lazyPages'
import { RouteErrorPage } from './RouteErrorPage'
const guardedRoutes = appRoutes.map((route) => ({ path: route.path === '/' ? undefined : route.path.slice(1), index: route.path === '/', element: route.path === '/' ? <DashboardPage /> : ['/content/sessions', '/content/programs', '/content/materials'].includes(route.path) ? <RequirePermission requiredPermissions={route.requiredPermissions}><Navigate replace to={'/content?type=' + route.path.split('/').at(-1)!.slice(0, -1)} /></RequirePermission> : route.path === '/content' ? <RequirePermission requiredPermissions={route.requiredPermissions}><ContentPage /></RequirePermission> : route.path === '/content/sessions/new' ? <RequirePermission requiredPermissions={route.requiredPermissions}><CreateResourcePage resourceType="session" /></RequirePermission> : route.path === '/content/materials/new' ? <RequirePermission requiredPermissions={route.requiredPermissions}><CreateResourcePage resourceType="material" /></RequirePermission> : route.path === '/content/programs/new' ? <RequirePermission requiredPermissions={route.requiredPermissions}><CreateProgramPage /></RequirePermission> : route.path === '/content/programs/:resourceId' ? <RequirePermission requiredPermissions={route.requiredPermissions}><ProgramEditorPage /></RequirePermission> : route.path === '/content/sessions/:resourceId' ? <RequirePermission requiredPermissions={route.requiredPermissions}><ResourceDetailPage expectedType="session" /></RequirePermission> : route.path === '/content/materials/:resourceId' ? <RequirePermission requiredPermissions={route.requiredPermissions}><ResourceDetailPage expectedType="material" /></RequirePermission> : route.path === '/media' ? <RequirePermission requiredPermissions={route.requiredPermissions}><MediaLibraryPage /></RequirePermission> : route.path === '/releases' || route.path === '/releases/:releaseId' ? <RequirePermission requiredPermissions={route.requiredPermissions}><ReleasesPage /></RequirePermission> : route.path === '/releases/new' ? <RequirePermission requiredPermissions={route.requiredPermissions}><ReleaseComposerPage /></RequirePermission> : route.path === '/commerce/products' ? <RequirePermission requiredPermissions={route.requiredPermissions}><ProductsPage /></RequirePermission> : route.path === '/commerce/products/:productId' ? <RequirePermission requiredPermissions={route.requiredPermissions}><ProductDetailPage /></RequirePermission> : route.path === '/users' ? <RequirePermission requiredPermissions={route.requiredPermissions}><UsersPage /></RequirePermission> : route.path === '/users/:userId' ? <RequirePermission requiredPermissions={route.requiredPermissions}><UserDetailPage /></RequirePermission> : <RequirePermission requiredPermissions={route.requiredPermissions} /> }))
export const router = createBrowserRouter([{ path: '/login', element: <RouteBoundary><LoginPage /></RouteBoundary>, errorElement: <RouteErrorPage /> }, { element: <RequireAuth />, errorElement: <RouteErrorPage />, children: [{ element: <RouteBoundary><AppShell /></RouteBoundary>, errorElement: <RouteErrorPage />, children: guardedRoutes }] }])

