import { JsonPreview } from '../../components/forms/JsonPreview'
import ArrowBackOutlined from '@mui/icons-material/ArrowBackOutlined'
import ReplayOutlined from '@mui/icons-material/ReplayOutlined'
import { Alert, Box, Button, Chip, FormControl, InputLabel, MenuItem, Paper, Select, Stack, Tab, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Tabs, TextField, Typography } from '@mui/material'
import { useQuery } from '@tanstack/react-query'
import { useEffect, useState } from 'react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { ApiError } from '../../api/apiError'
import { hasAnyPermission } from '../../auth/permissions'
import { useAuth } from '../../auth/useAuth'
import { fetchUser, fetchUserAccess, fetchUserOrders, fetchUserProgress, fetchUsers, formatGroszeAsPln, type CursorPage, type UserListSearch } from './userApi'

const pageSizes = [25, 50, 100] as const
type DetailTab = 'profile' | 'access' | 'orders' | 'progress'

function getSearch(params: URLSearchParams): UserListSearch { const search = params.get('search')?.trim(); const pageSize = Number(params.get('pageSize') ?? 25); return { ...(search && search.length >= 2 ? { search } : {}), pageSize: pageSizes.includes(pageSize as 25 | 50 | 100) ? pageSize as 25 | 50 | 100 : 25, ...(params.get('cursor') ? { cursor: params.get('cursor')! } : {}) } }
function formatDate(value: string | null): string { return value ? new Intl.DateTimeFormat('pl-PL', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'UTC' }).format(new Date(value)) : 'Brak' }
function tabProps(tab: DetailTab) { return { id: `user-tab-${tab}`, 'aria-controls': `user-panel-${tab}` } }

export function UsersPage() {
  const [params, setParams] = useSearchParams(); const [cursorStack, setCursorStack] = useState<string[]>([]); const search = getSearch(params); const query = useQuery({ queryKey: ['users', search], queryFn: ({ signal }) => fetchUsers(search, signal) })
  const updateSearch = (key: 'search' | 'pageSize', value: string) => { const next = new URLSearchParams(params); next.delete('cursor'); if (value) next.set(key, value); else next.delete(key); setCursorStack([]); setParams(next) }
  const changePage = (cursor?: string) => { const next = new URLSearchParams(params); if (cursor) next.set('cursor', cursor); else next.delete('cursor'); setParams(next) }
  return <Box sx={{ maxWidth: 1440, p: { xs: 2, sm: 4 } }}><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2} sx={{ alignItems: { sm: 'flex-start' }, justifyContent: 'space-between', mb: 3 }}><Box><Typography component="h1" variant="h3">Użytkownicy</Typography><Typography color="text.secondary" sx={{ mt: 1 }}>Dane pomocnicze kont i historii klienta, wyłącznie do odczytu.</Typography></Box></Stack><Paper elevation={0} sx={{ border: '1px solid', borderColor: 'divider', mb: 3, p: 2.5 }}><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><UserSearch initialValue={search.search ?? ''} onChange={(value) => updateSearch('search', value)} /><FormControl size="small" sx={{ minWidth: 150 }}><InputLabel>Na stronie</InputLabel><Select label="Na stronie" onChange={(event) => updateSearch('pageSize', event.target.value)} value={String(search.pageSize)}>{pageSizes.map((size) => <MenuItem key={size} value={size}>{size}</MenuItem>)}</Select></FormControl></Stack></Paper>{query.isPending && <Typography aria-live="polite">Ładowanie użytkowników...</Typography>}{query.isError && <Alert action={<Button color="inherit" onClick={() => void query.refetch()} startIcon={<ReplayOutlined />}>Spróbuj ponownie</Button>} severity="error">Nie udało się pobrać użytkowników.</Alert>}{query.isSuccess && query.data.items.length === 0 && <Alert severity="info">Brak użytkowników dla podanego wyszukiwania.</Alert>}{query.data && <><TableContainer component={Paper} elevation={0} sx={{ border: '1px solid', borderColor: 'divider' }}><Table><TableHead><TableRow><TableCell>Użytkownik</TableCell><TableCell>E-mail</TableCell><TableCell>Metoda logowania</TableCell><TableCell>Utworzono</TableCell></TableRow></TableHead><TableBody>{query.data.items.map((user) => <TableRow hover key={user.userId}><TableCell><Button component={Link} to={`/users/${user.userId}`}>{user.displayName ?? 'Bez nazwy'}</Button><Typography color="text.secondary" variant="body2">{user.userId}</Typography></TableCell><TableCell>{user.email ?? 'Brak'}</TableCell><TableCell>{user.authProvider}</TableCell><TableCell>{formatDate(user.createdAt)}</TableCell></TableRow>)}</TableBody></Table></TableContainer><CursorPagination page={query.data} onNext={() => { if (query.data.nextCursor) { setCursorStack((items) => [...items, search.cursor ?? '']); changePage(query.data.nextCursor) } }} onPrevious={() => { const previous = cursorStack.at(-1); setCursorStack((items) => items.slice(0, -1)); changePage(previous) }} previousEnabled={cursorStack.length > 0} /></>}</Box>
}

function UserSearch({ initialValue, onChange }: { initialValue: string; onChange: (value: string) => void }) { const [value, setValue] = useState(initialValue); useEffect(() => { const timer = window.setTimeout(() => { const next = value.trim(); if (next === initialValue || (next.length > 0 && next.length < 2)) return; onChange(next) }, 300); return () => window.clearTimeout(timer) }, [initialValue, onChange, value]); return <TextField helperText={value.trim().length === 1 ? 'Wpisz co najmniej 2 znaki.' : undefined} label="Szukaj użytkownika" onChange={(event) => setValue(event.target.value)} size="small" value={value} sx={{ minWidth: { xs: 0, sm: 280 } }} /> }

export function UserDetailPage() {
  const { permissions } = useAuth(); const { userId = '' } = useParams(); const canReadAccess = hasAnyPermission(permissions, ['access.read']); const [tab, setTab] = useState<DetailTab>('profile'); const activeTab = !canReadAccess && tab === 'access' ? 'profile' : tab; const detail = useQuery({ queryKey: ['user', userId], queryFn: ({ signal }) => fetchUser(userId, signal) })
  if (detail.isPending) return <Box sx={{ p: { xs: 2, md: 4 } }}><Typography aria-live="polite">Ładowanie użytkownika...</Typography></Box>
  if (detail.isError) { const absent = detail.error instanceof ApiError && detail.error.status === 404; return <Box sx={{ maxWidth: 900, p: { xs: 2, md: 4 } }}><Alert action={!absent && <Button color="inherit" onClick={() => void detail.refetch()} startIcon={<ReplayOutlined />}>Spróbuj ponownie</Button>} severity="error">{absent ? 'Nie znaleziono użytkownika.' : 'Nie udało się pobrać użytkownika.'}</Alert></Box> }
  const user = detail.data
  return <Box sx={{ maxWidth: 1200, p: { xs: 2, sm: 4 } }}><Button component={Link} startIcon={<ArrowBackOutlined />} to="/users">Wróć do użytkowników</Button><Box sx={{ mb: 3, mt: 2 }}><Typography component="h1" variant="h3">{user.displayName ?? 'Bez nazwy'}</Typography><Typography color="text.secondary" sx={{ overflowWrap: 'anywhere' }}>ID użytkownika: {user.userId}</Typography></Box><Tabs aria-label="Dane użytkownika" onChange={(_, value: DetailTab) => setTab(value)} value={activeTab} variant="scrollable"> <Tab label="Profil" value="profile" {...tabProps('profile')} />{canReadAccess && <Tab label="Dostęp" value="access" {...tabProps('access')} />}<Tab label="Zamówienia" value="orders" {...tabProps('orders')} /><Tab label="Postęp" value="progress" {...tabProps('progress')} /></Tabs><Box role="tabpanel" id={`user-panel-${activeTab}`} aria-labelledby={`user-tab-${activeTab}`} sx={{ pt: 3 }}>{activeTab === 'profile' && <ProfileTab user={user} />}{activeTab === 'access' && canReadAccess && <AccessTab userId={userId} />}{activeTab === 'orders' && <OrdersTab userId={userId} />}{activeTab === 'progress' && <ProgressTab userId={userId} />}</Box></Box>
}

function ProfileTab({ user }: { user: Awaited<ReturnType<typeof fetchUser>> }) { return <Paper elevation={0} sx={{ border: '1px solid', borderColor: 'divider', p: { xs: 2, sm: 3 } }}><Typography component="h2" variant="h5">Profil</Typography><Alert severity="info" sx={{ mt: 2 }}>Dane konta są tylko do odczytu. API nie udostępnia jeszcze ich zapisu w panelu.</Alert><Stack spacing={1.25} sx={{ mt: 2 }}><Detail label="Nazwa wyświetlana" value={user.displayName} /><Detail label="E-mail" value={user.email} /><Detail label="Imię" value={user.firstName} /><Detail label="Nazwisko" value={user.lastName} /><Detail label="Metoda logowania" value={user.authProvider} /><Detail label="Język" value={user.locale} /><Detail label="Strefa czasowa" value={user.timeZone} /><Detail label="Powiadomienia" value={user.notificationsEnabled ? 'Włączone' : 'Wyłączone'} /><Detail label="Motyw" value={user.theme} /><Detail label="Utworzono" value={formatDate(user.createdAt)} /><Detail label="Zaktualizowano" value={formatDate(user.updatedAt)} /><JsonPreview label="Profil użytkownika (JSON)" value={user} /></Stack></Paper> }
function Detail({ label, value }: { label: string; value: string | null }) { return <TextField label={label} value={value ?? ''} placeholder="Brak" fullWidth slotProps={{ input: { readOnly: true } }} /> }
function AccessTab({ userId }: { userId: string }) { const query = useQuery({ queryKey: ['user', userId, 'access'], queryFn: ({ signal }) => fetchUserAccess(userId, signal) }); return <QueryPanel query={query} empty="Brak aktywnego lub historycznego dostępu do wyświetlenia." failure="Nie udało się pobrać dostępu użytkownika." render={(data) => <TableContainer component={Paper} elevation={0} sx={{ border: '1px solid', borderColor: 'divider' }}><Table><TableHead><TableRow><TableCell>Zakres</TableCell><TableCell>Źródło</TableCell><TableCell>Obowiązuje</TableCell><TableCell>Status</TableCell></TableRow></TableHead><TableBody>{data.items.map((item) => <TableRow key={item.grantId}><TableCell>{item.entitlementKey ?? item.resourceKey ?? item.scope}</TableCell><TableCell>{item.source}</TableCell><TableCell>{formatDate(item.validFrom)} - {formatDate(item.validUntil)}</TableCell><TableCell><Chip color={item.revokedAt ? 'default' : 'success'} label={item.revokedAt ? 'Cofnięty' : 'Aktywny'} size="small" /></TableCell></TableRow>)}</TableBody></Table></TableContainer>} /> }
function OrdersTab({ userId }: { userId: string }) { return <PagedTab queryKey={['user', userId, 'orders']} fetchPage={(search, signal) => fetchUserOrders(userId, search, signal)} empty="Brak zamówień do wyświetlenia." failure="Nie udało się pobrać zamówień użytkownika." render={(items) => <TableContainer component={Paper} elevation={0} sx={{ border: '1px solid', borderColor: 'divider' }}><Table><TableHead><TableRow><TableCell>Produkt</TableCell><TableCell>Kwota</TableCell><TableCell>Status</TableCell><TableCell>Utworzono</TableCell></TableRow></TableHead><TableBody>{items.map((item) => <TableRow key={item.orderId}><TableCell>{item.productTitle}</TableCell><TableCell>{item.currency === 'PLN' ? formatGroszeAsPln(item.amountInGrosze) : item.currency}</TableCell><TableCell>{item.status}</TableCell><TableCell>{formatDate(item.createdAt)}</TableCell></TableRow>)}</TableBody></Table></TableContainer>} /> }
function ProgressTab({ userId }: { userId: string }) { return <PagedTab queryKey={['user', userId, 'progress']} fetchPage={(search, signal) => fetchUserProgress(userId, search, signal)} empty="Brak postępu do wyświetlenia." failure="Nie udało się pobrać postępu użytkownika." render={(items) => <TableContainer component={Paper} elevation={0} sx={{ border: '1px solid', borderColor: 'divider' }}><Table><TableHead><TableRow><TableCell>Materiał</TableCell><TableCell>Pozycja</TableCell><TableCell>Status</TableCell><TableCell>Zaktualizowano</TableCell></TableRow></TableHead><TableBody>{items.map((item) => <TableRow key={item.resourceId}><TableCell>{item.resourceKey}</TableCell><TableCell>{item.positionSeconds} s</TableCell><TableCell>{item.isCompleted ? 'Ukończono' : 'W trakcie'}</TableCell><TableCell>{formatDate(item.updatedAt)}</TableCell></TableRow>)}</TableBody></Table></TableContainer>} /> }
function PagedTab<T>({ queryKey, fetchPage, empty, failure, render }: { queryKey: readonly string[]; fetchPage: (search: UserListSearch, signal?: AbortSignal) => Promise<CursorPage<T>>; empty: string; failure: string; render: (items: T[]) => React.ReactNode }) { const [cursor, setCursor] = useState<string>(); const [previous, setPrevious] = useState<string[]>([]); const query = useQuery({ queryKey: [...queryKey, cursor], queryFn: ({ signal }) => fetchPage({ pageSize: 25, ...(cursor ? { cursor } : {}) }, signal) }); return <QueryPanel query={query} empty={empty} failure={failure} render={(page) => <>{render(page.items)}<CursorPagination page={page} onNext={() => { if (page.nextCursor) { setPrevious((items) => [...items, cursor ?? '']); setCursor(page.nextCursor) } }} onPrevious={() => { const next = previous.at(-1); setPrevious((items) => items.slice(0, -1)); setCursor(next) }} previousEnabled={previous.length > 0} /></>} /> }
function QueryPanel<T>({ query, empty, failure, render }: { query: ReturnType<typeof useQuery<T>>; empty: string; failure: string; render: (data: T) => React.ReactNode }) { if (query.isPending) return <Typography aria-live="polite">Ładowanie...</Typography>; if (query.isError) return <Alert action={<Button color="inherit" onClick={() => void query.refetch()} startIcon={<ReplayOutlined />}>Spróbuj ponownie</Button>} severity="error">{failure}</Alert>; if (Array.isArray((query.data as { items?: unknown[] }).items) && (query.data as { items: unknown[] }).items.length === 0) return <Alert severity="info">{empty}</Alert>; return <>{render(query.data)}</> }
function CursorPagination<T>({ page, onNext, onPrevious, previousEnabled }: { page: CursorPage<T>; onNext: () => void; onPrevious: () => void; previousEnabled: boolean }) { return <Stack direction="row" spacing={1} sx={{ justifyContent: 'flex-end', mt: 2 }}><Button disabled={!previousEnabled} onClick={onPrevious}>Poprzednia</Button><Button disabled={!page.nextCursor} onClick={onNext} variant="outlined">Następna</Button></Stack> }

